export const postagens = [
	{
		id: 0,
		date: "March 22nd",
		p1: "Today I learned soo many things, some stuff I already knew, but many of them I never had heard about. There's so many categories that I've known for so long and others that I haven't. Summarizing everything, I've learned how words are formed, lot's of them I knew, but It was funny knowing more about it.",
		p2: "I really liked learning all of the ways a word can be formed, and how it changes (or not) the meaning. I kinda like the affixes, they are so usefull and, OMG I just thought about something: if you know the meaning of one of these, you instantly learn a bunch of new words, for example: the words ending -ful, is used for something in quantity, like useful, beautiful, painful. I really like that.",
		p3: "I took some notes, so I think I got the main points of what the teacher showed us, but I have to study a little bit more by my self to fix all the concepts and examples in my mind. There was so many new concepts that I’m afraid of mix some of them and go crazy on the tests.",
		p4: "I just remembered the classes in my second Teaching Practicum at UNEB, where me and Vitor taught our students a little about how word formation can help them read better not only English texts but Portuguese and so on. Knowing that helps you guess the meaning of a word you don’t know (in theory). So I believe it really help in reading, and I will always use this in my classes.",
		p5: "🧠🧠🧠🧠🧠 5 brains out of 5.",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 1,
		date: "March 29th",
		p1: "Today we had to remember many things that we learned last class and learn new ones. One particular thing that I never thought about was how dictionaries are made. They don't have a section for other variations or derivations of the same root. That's kinda strange because this means we have to know more about the language to use them, but at the same time, we as teachers, are used to use 'em in our classes without thinking about that.",
		p2: "I enjoyed our discussions about the vision our country has when we talk about teachers, it's rooted in our society. The people see a person who went abroad as capable as a person who took four years or more in an University to be capable to teach a language. I can't teach portuguese just because I'm brazilian, I personally suck at it. I believe that we have to policy ourselves because of that, we are capable of teach even though we don't have experiences in another country, or the fluency they expect from us.",
		p3: "I think I got how the basics of Morphology works, but some of the concepts still obscure in my mind, for example the Allomorphs, I have to look up this concept to understand it better. So I think think that was my weakness this week.",
		p4: "I know it's now related to the subject we studied, but the topic discussed in our class on this day clarified some things to me. I know now that I have an important acting role in our society, give my best to teach what I have been learning though these 5 years of UNEB, and showing them, even though I haven't attended a private course or travelled abroad, I have the skills to teach english to my students. And I'll keep improving every day on my own.",
		p5: "🦐🦐🦐🦐 4 shrimps out of 5.",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 2,
		date: "April 5th",
		p1: "Today was a bit different from the other classes, because we had a test which involved the subjects we had on the previous classes, and it was really fun to do. The interesting part of it was to be able to discuss my solutions with my colleague Vitor, we helped each other by showing concepts we forgot at the moment.",
		p2: "I think the test method that the professor used. It was different and I really enjoyed it.",
		p3: "I understood how the test was going to work, but some of my colleagues didn't understand at that time, so I could feel their concerns.",
		p4: "I should try this at some time in my life, it encourages students to think more about their response and gives to the student a different feeling when taking a test.",
		p5: "👽👽👽👽👽 5 aliens out of 5.",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
];
