export const postagens = [
	{
		id: 0,
		date: "March 22nd",
		p1: "Today I learned soo many things, some stuff I already knew, but many of them I never had heard about. There's so many categories that I've known for so long and others that I haven't. Summarizing everything, I've learned how words are formed, lot's of them I knew, but It was funny knowing more about it.",
		p2: "I really liked learning all of the ways a word can be formed, and how it changes (or not) the meaning. I kinda like the affixes, they are so usefull and, OMG I just thought about something: if you know the meaning of one of these, you instantly learn a bunch of new words, for example: the words ending -ful, is used for something in quantity, like useful, beautiful, painful. I really like that.",
		p3: "I took some notes, so I think I got the main points of what the teacher showed us, but I have to study a little bit more by my self to fix all the concepts and examples in my mind. There was so many new concepts that I’m afraid of mix some of them and go crazy on the tests.",
		p4: "I just remembered the classes in my second Teaching Practicum at UNEB, where me and Vitor taught our students a little about how word formation can help them read better not only English texts but Portuguese and so on. Knowing that helps you guess the meaning of a word you don’t know (in theory). So I believe it really help in reading, and I will always use this in my classes.",
		p5: "🧠🧠🧠🧠🧠 5 brains out of 5.",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 1,
		date: "March 29th",
		p1: "Today we had to remember many things that we learned last class and learn new ones. One particular thing that I never thought about was how dictionaries are made. They don't have a section for other variations or derivations of the same root. That's kinda strange because this means we have to know more about the language to use them, but at the same time, we as teachers, are used to use 'em in our classes without thinking about that.",
		p2: "I enjoyed our discussions about the vision our country has when we talk about teachers, it's rooted in our society. The people see a person who went abroad as capable as a person who took four years or more in an University to be capable to teach a language. I can't teach portuguese just because I'm brazilian, I personally suck at it. I believe that we have to policy ourselves because of that, we are capable of teach even though we don't have experiences in another country, or the fluency they expect from us.",
		p3: "I think I got how the basics of Morphology works, but some of the concepts still obscure in my mind, for example the Allomorphs, I have to look up this concept to understand it better. So I think think that was my weakness this week.",
		p4: "I know it's now related to the subject we studied, but the topic discussed in our class on this day clarified some things to me. I know now that I have an important acting role in our society, give my best to teach what I have been learning though these 5 years of UNEB, and showing them, even though I haven't attended a private course or travelled abroad, I have the skills to teach english to my students. And I'll keep improving every day on my own.",
		p5: "🦐🦐🦐🦐 4 shrimps out of 5.",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 2,
		date: "April 5th",
		p1: "Today was a bit different from the other classes, because we had a test which involved the subjects we had on the previous classes, and it was really fun to do. The interesting part of it was to be able to discuss my solutions with my colleague Vitor, we helped each other by showing concepts we forgot at the moment.",
		p2: "I think the test method that the professor used. It was different and I really enjoyed it.",
		p3: "I understood how the test was going to work, but some of my colleagues didn't understand at that time, so I could feel their concerns.",
		p4: "I should try this at some time in my life, it encourages students to think more about their response and gives to the student a different feeling when taking a test.",
		p5: "👽👽👽👽👽 5 aliens out of 5.",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 3,
		date: "April 19th",
		p1: "In today's class we has a more easy subject to study. We've learned how words can be fomed! There are many types of word formation: Coinage, when we use brand names as the names of the objects. Borrowing: When we borrow some words from other languages and incorporates them in ours. Compounding: When we put together two word to form a new one. Blending: When we put parts of two words together and creates a new one. Clipping: When we cut a long word and create a shorter version of it to use. To be honest, I didn't understand what `BACKFORMATION` is, so I think I'll have to study it a little more. Conversion: When we use the same word that has a different meaning like `BALEIA BALEIA BALEIA` so in this example, a whale shoots another whale, and finally, acronyms: using acronyms like WHO: World Heath Organization and many others.",
		p2: "I really like the affixes part. It's something that I've searched for, and I belive they are very interesting to know.",
		p3: "The activities were funny to do. There are some concepts that I didn't understand and as I said before, I have to study more about.",
		p4: "The affixes is something I really enjoyed teach at my last Teaching Practice Internship. So, I really want to show them for my students, not in this semester, because they are new in english classes, but who knows in the next one when I will have to teach older students in the state schools.",
		p5: "🫠🫠🫠🫠🫠 5 out of 5 melting dudes (because it's too hot today)",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 4,
		date: "April 26th",
		p1: "We had a test today. It was a really easy and I had to study a little more about the concepts we've learned in the previous class, and fix them in my mind.",
		p2: "The LARGE range of word formation types are really interesting, I was cofusing some of them but I believe I did it well.",
		p3: "I think everything worked well. Everyone now knows how important is knowing this subject because they tell us more than its meaning, I believe.",
		p4: "As I said before, knowing how the words are formed, I can predict the word's meaning, even though I don't know it's meaning in the first time reading them.",
		p5: "🦋🦋🦋🦋🦋 5 out of 5 butterflies",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 5,
		date: "May 3rd",
		p1: "Today was a bit different, because we didn't have class. So we had to read the texts that the send to us. It was simple, because we learned the parts of speech and some words classifications.",
		p2: "The adverbs part. It was really interesting, because I didn't know exactly what it was.",
		p3: "I think everything worked well.",
		p4: "Knowing this classifications I can improve my classes with those definitions.",
		p5: "🍀🍀🍀🍀🍀 5 out of 5 clovers",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 6,
		date: "May 10th",
		p1: "We had a test today. Following the subject difficulty we had last week, it was easy. We had the chance to check our knoledge about the parts of speech.",
		p2: "I like that I was too confident in the test. Although I may have switched two concepts in the test, which made me fail the questions.",
		p3: "Except the misconceptions in the two questions I said before, I think everything worked very well.",
		p4: "Discussing these concepts is something really important, because the students can distinguish the words and know where to use them.",
		p5: "🐲🐲🐲🐲🐲 5 out of 5 dragons",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
	{
		id: 7,
		date: "May 17th",
		p1: "I missed this class because I was feeling under the weather that day. So, I had to study though the slides presentation the teacher made. I learned that we may get confused by some words we have in our mother language or in English. Working in translations doesn't mean translate the text directly (word by word), the languages have different structures even though they are simillar or have similar words. So, we have to pay attention to that.",
		p2: "Knowing that we have the power of conveying meaning through languages. If there's a mistake (even the smallest one) in the translation, this can change a whole comprehension idea of the text piece.",
		p3: "I think I could have understood better in the class, perhaps the professor could have given many other examples or I could have heard some other explanations from her.",
		p4: "This subject is really important for our students to know, because this can help them to understand better the texts they read in class or in any other place.",
		p5: "🦁🦁🦁🦁🦁 5 out of 5 lions",
		img: "https://raw.githubusercontent.com/tozeos/learning-log/master/src/assets/Tomnook.png",
	},
];
